# Permalinks
permalink:        /:title
baseurl:          '/'

markdown:         kramdown
highlighter:      pygments

# Setup
title:            Masoumeh Haghpanahi
tagline:          ''
url:              http://mashagh.github.io

author:
  name:           'Masoumeh Haghpanahi'
  url:            http://mashagh.github.io

# Custom vars
github:           https://github.com/mashagh
home_posts:       1
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'