# Permalinks
permalink:        /blog/:title
baseurl:          '/'

markdown:         kramdown
highlighter:      pygments

# Setup
title:            Masoud Rabiei
tagline:          Data science and beyond
url:              http://masrab.github.io
paginate:         1

author:
  name:           'Masoud Rabiei'
  url:            http://www.masrab.com

# Custom vars
github:           https://github.com/masrab
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'